import { useState } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { ConfirmDialog } from '@/components/ui/ConfirmDialog';
import { Modal } from '@/components/ui/Modal';
import { Select } from '@/components/ui/Select';
import { useAuth } from '@/hooks/useAuth';
import { useProjectMemberMutations, useProjectMembers, useProjectUserOptions } from '@/hooks/useProjects';
import type { ProjectRole } from '@/types';

export function ProjectMembersPage() {
  const id = Number(useParams().id); const { hasPermission } = useAuth(); const { data, isLoading, isError } = useProjectMembers(id); const { data: options } = useProjectUserOptions(hasPermission('project.manage_members')); const { addMember, updateMember, removeMember } = useProjectMemberMutations(id); const [open, setOpen] = useState(false); const [removeId, setRemoveId] = useState<number | null>(null); const [userId, setUserId] = useState(''); const [role, setRole] = useState<ProjectRole>('member');
  const add = async (event: React.FormEvent) => { event.preventDefault(); try { await addMember.mutateAsync({ user_id: Number(userId), project_role: role }); setOpen(false); toast.success('Anggota ditambahkan.'); } catch { toast.error('Anggota gagal ditambahkan atau sudah terdaftar.'); } };
  return <div className="space-y-5"><Link to={`/projects/${id}`} className="inline-flex items-center gap-2 text-sm font-medium text-blue-600"><ArrowLeft className="h-4 w-4" />Kembali ke project</Link><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Project Members</h1><p className="mt-1 text-sm text-slate-500">Kelola akses dan project role.</p></div>{hasPermission('project.manage_members') && <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Tambah anggota</Button>}</div>{isLoading ? <div className="py-12 text-center">Memuat anggota...</div> : isError ? <div className="text-red-600">Anggota gagal dimuat.</div> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Nama</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Project Role</th><th className="px-4 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.data.map((member) => <tr key={member.id}><td className="px-4 py-3 font-medium">{member.user?.name}</td><td className="px-4 py-3 text-slate-600">{member.user?.email}</td><td className="px-4 py-3">{hasPermission('project.manage_members') ? <Select options={roleOptions} value={member.project_role} onChange={(event) => updateMember.mutate({ memberId: member.id, payload: { user_id: member.user_id, project_role: event.target.value as ProjectRole } })} /> : <Badge>{member.project_role}</Badge>}</td><td className="px-4 py-3 text-right">{hasPermission('project.manage_members') && <Button variant="ghost" size="sm" onClick={() => setRemoveId(member.id)}><Trash2 className="h-4 w-4 text-red-600" /></Button>}</td></tr>)}</tbody></table></div>}<Modal isOpen={open} onClose={() => setOpen(false)} title="Tambah anggota"><form onSubmit={add} className="space-y-4"><Select label="Pengguna" options={(options?.data ?? []).map((user) => ({ value: String(user.id), label: `${user.name} — ${user.email}` }))} placeholder="Pilih pengguna" value={userId} onChange={(event) => setUserId(event.target.value)} required /><Select label="Project role" options={roleOptions} value={role} onChange={(event) => setRole(event.target.value as ProjectRole)} /><div className="flex justify-end"><Button type="submit" isLoading={addMember.isPending}>Simpan</Button></div></form></Modal><ConfirmDialog isOpen={removeId !== null} title="Hapus anggota" message="Anggota akan kehilangan akses ke project dan task terkait." onClose={() => setRemoveId(null)} onConfirm={() => { if (removeId !== null) removeMember.mutate(removeId, { onSuccess: () => setRemoveId(null) }); }} isLoading={removeMember.isPending} /></div>;
}
const roleOptions = [{ value: 'manager', label: 'Manager' }, { value: 'member', label: 'Member' }, { value: 'viewer', label: 'Viewer' }];
